#!/bin/bash

# WebGL Fuzzing Corpus - Next Test Case Implementation
# This script provides instructions for implementing the next WebGL test case

echo "🚀 WebGL Fuzzing Corpus - Next Test Case Implementation"
echo "======================================================"
echo ""

echo "📋 CURRENT STATUS:"
echo "Based on WEBGL_FUZZING_CORPUS_PROGRESS.md:"
echo "✅ Completed: 6/61 test cases (9.8%)"
echo "🔲 Next Priority: Category 1 - Core Pipeline Components"
echo ""

echo "🎯 NEXT TEST CASE TO IMPLEMENT:"
echo "WEBGL-INT-003: Extension Soup"
echo "- Query all extensions, use one feature from each"
echo "- Focus on extension availability testing and feature combinations"
echo "- Biomass: All extensions, feature combinations"
echo ""

echo "📚 REQUIRED READING (in order):"
echo "1. WEBGL_IMPLEMENTATION_PLAN.md - Overall strategy and specifications"
echo "2. WEBGL_FUZZING_CORPUS_PROGRESS.md - Current status and next priorities"
echo "3. AGENTS.md - Technical implementation guidelines"
echo "4. CODING_RULES.md - Code quality standards and testing procedures"
echo ""

echo "🛠️  IMPLEMENTATION WORKFLOW:"
echo ""
echo "Step 1: Feature Analysis"
echo "--------"
echo "• Read WEBGL-INT-003 specification from implementation plan"
echo "• Identify target extensions and their features"
echo "• Plan how to combine multiple extensions in single test"
echo "• Check UNSUPPORTED.md for known limitations"
echo ""
echo "Step 2: Code Implementation"
echo "--------"
echo "• Use boilerplate from AGENTS.md"
echo "• Create REQUIRED_EXTENSIONS array with all target extensions"
echo "• Implement extension checking and graceful fallback"
echo "• Combine multiple extension features in complex rendering"
echo "• Mix inline literals with parameterized variables for fuzzing"
echo "• Include state poisoning patterns"
echo ""
echo "Step 3: Testing & Validation"
echo "--------"
echo "• Save file to agent_outputs/extension_soup.html"
echo "• Run: ./run_tests.sh --test-file agent_outputs/extension_soup.html --browsers chromium"
echo "• Verify: PASSED with 0 errors/warnings"
echo "• Check generated .json file for success criteria"
echo ""
echo "Step 4: Documentation Update"
echo "--------"
echo "• Update WEBGL_FUZZING_CORPUS_PROGRESS.md"
echo "• Change WEBGL-INT-003 status from 🔲 to ✅"
echo "• Add filename to File column"
echo "• Update implementation session log"
echo "• Update coverage metrics"
echo ""

echo "🎨 IMPLEMENTATION SPECIFICS:"
echo ""
echo "Extensions to Target (prioritize availability):"
echo "• OES_texture_float - Float textures"
echo "• WEBGL_draw_buffers - Multiple render targets"
echo "• OES_vertex_array_object - VAO management"
echo "• ANGLE_instanced_arrays - Instanced rendering"
echo "• WEBGL_depth_texture - Depth textures"
echo "• OES_standard_derivatives - Shader derivatives"
echo ""
echo "Key Requirements:"
echo "• Query all extensions systematically"
echo "• Use at least one feature from each available extension"
echo "• Combine features in complex rendering pipeline"
echo "• Handle extension unavailability gracefully"
echo "• Create visually complex output demonstrating all features"
echo "• Include 50+ state changes and resource bindings"
echo ""

echo "🔍 VALIDATION CHECKLIST:"
echo "• [ ] File created: agent_outputs/extension_soup.html"
echo "• [ ] Extension checking implemented"
echo "• [ ] Multiple extensions combined in single test"
echo "• [ ] State poisoning patterns included"
echo "• [ ] Fuzzing-friendly variable exposure"
echo "• [ ] Test passes: ./run_tests.sh returns PASSED"
echo "• [ ] JSON output shows 0 errors/warnings"
echo "• [ ] Progress file updated with ✅ status"
echo ""

echo "⚡ QUICK REFERENCE:"
echo "Boilerplate: AGENTS.md Section 'WebGL Setup'"
echo "Testing: ./run_tests.sh --test-file FILE --browsers chromium"
echo "Progress: Update WEBGL_FUZZING_CORPUS_PROGRESS.md"
echo "Success: PASSED + 0 errors/warnings + progress updated"
echo ""

echo "🎯 START IMPLEMENTATION NOW"
echo "==========================="
echo ""
echo "Ready to implement WEBGL-INT-003: Extension Soup?"
echo "Follow the workflow above and update progress when complete."