#!/bin/bash
# WebGL Test Runner - Easy launcher script

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}🚀 WebGL Test Runner${NC}"

# Check if virtual environment exists
if [ -d "venv" ]; then
    echo -e "${GREEN}📦 Using virtual environment${NC}"
    PYTHON_CMD="./venv/bin/python"
elif command -v python3 &> /dev/null; then
    echo -e "${YELLOW}⚠️  Using system Python3${NC}"
    PYTHON_CMD="python3"
elif command -v python &> /dev/null; then
    echo -e "${YELLOW}⚠️  Using system Python${NC}"
    PYTHON_CMD="python"
else
    echo -e "${RED}❌ Python not found${NC}"
    exit 1
fi

# Check if setup is needed
if [ ! -d "venv" ] && [ ! -f "webgl_test_runner.py" ]; then
    echo -e "${YELLOW}💡 Run setup first: python3 setup_test_runner.py${NC}"
    exit 1
fi

# Show help if requested
if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    echo -e "${GREEN}🚀 WebGL Test Runner${NC}"
    echo ""
    echo "Usage: $0 [options]"
    echo ""
    echo "Browser Configuration:"
    echo "  --browser-config FILE     Use browser configuration JSON file"
    echo "  --chromium-path PATH      Custom Chromium/Chrome executable path"  
    echo "  --firefox-path PATH       Custom Firefox executable path"
    echo "  --webkit-path PATH        Custom WebKit executable path"
    echo ""
    echo "Examples:"
    echo "  $0 --chromium-path /usr/bin/google-chrome-beta"
    echo "  $0 --browser-config my_browsers.json --browsers chromium firefox"
    echo "  $0 --firefox-path /usr/bin/firefox-nightly --browsers firefox"
    echo "  $0 --html                                    # Generate HTML report"
    echo ""
    echo "Note: JSON output is generated by default"
    echo ""
    echo "For full options, run: $PYTHON_CMD webgl_test_runner.py --help"
    echo "For browser detection: python3 detect_browsers.py"
    exit 0
fi

# Browser guidance
echo -e "${GREEN}Browser Selection Guide:${NC}"
echo -e "  • ${YELLOW}Firefox${NC}: Default browser (superior WebGL extension support)"
echo -e "  • ${GREEN}Chromium${NC}: Core WebGL + WebGL2 features (use --browsers chromium)"
echo ""

# Set default browser to firefox if not specified (better extension support)
if [[ "$*" != *"--browsers"* ]]; then
    echo -e "${YELLOW}⚠️  No browser specified, defaulting to firefox${NC}"
    echo -e "${YELLOW}💡 Firefox has superior WebGL extension support${NC}"
    set -- "$@" --browsers firefox
fi

# Run the test runner with all arguments
echo -e "${GREEN}🧪 Running tests...${NC}"

# Set environment variables for Firefox to match native Ubuntu behavior
if [[ "$*" == *"firefox"* ]]; then
    echo -e "${YELLOW}🔧 Setting Firefox environment variables for native compatibility...${NC}"
    export MOZ_X11_EGL=1
fi

$PYTHON_CMD webgl_test_runner.py "$@" 2>/dev/null
